<a href="https://colab.research.google.com/github/bhatimukul/Assignment-func/blob/main/Numpy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Theoretical Question:***

---



---

**Q1.Explain the purpose and advantages of Numpy in scientiic computing and data analysis. How does it enhance Python's capabilities for numerical operations?**

Ans. NumPy (Numerical Python) is a powerful library in Python that is essential for scientific computing and data analysis. It enhances Python's capabilities for numerical operations by providing support for efficient handling of large multidimensional arrays and matrices, along with a wide collection of mathematical functions. Here are the key purposes and advantages of using NumPy:

1. Efficient Array Handling

.Purpose:NumPy provides the ndarray (N-dimensional array) object, which is a highly optimized data structure for handling large datasets.

.Advantage: Compared to Python’s built-in lists, NumPy arrays are more memory-efficient and faster for operations on large datasets because they store data in contiguous memory locations. This allows NumPy to take advantage of low-level optimizations in C and Fortran, resulting in faster execution.
2. Mathematical Functions and Linear Algebra

.Purpose: NumPy provides a large set of mathematical functions such as trigonometric functions, algebraic functions, and statistical operations.

.Advantage: It simplifies complex mathematical operations by providing easy-to-use functions for matrix multiplication, solving linear equations, eigenvalues, and more. These operations are fundamental in scientific computing and data analysis and are optimized for speed and efficiency.
3. Vectorization and Broadcasting

.Purpose: NumPy allows operations on entire arrays without writing loops, which is known as vectorization. Broadcasting refers to performing operations on arrays of different shapes in a way that aligns dimensions automatically.

.Advantage: This feature removes the need for explicit loops, making code more concise, easier to read, and much faster due to underlying optimizations. It also makes working with arrays of different sizes simpler and more intuitive.
4. Integration with Other Libraries

.Purpose: NumPy is the foundation for many other scientific and data analysis libraries in Python, such as SciPy, Pandas, TensorFlow, and Matplotlib.

.Advantage: It seamlessly integrates with these libraries, making it the core of the scientific computing ecosystem in Python. For instance, Pandas uses NumPy arrays for its DataFrame structures, and Matplotlib uses NumPy for efficient plotting of large datasets.
5. Handling Large Datasets

.Purpose: NumPy provides support for handling and processing large datasets efficiently.

.Advantage: Since NumPy arrays are more compact and computationally efficient compared to Python lists, they are better suited for handling large amounts of data that are common in fields like data science, machine learning, and computational physics.
6. Interfacing with C/C++ and Fortran

.Purpose: NumPy can interface directly with code written in C, C++, or Fortran, which are often used in high-performance computing.

.Advantage: This allows developers to write performance-critical sections of code in these languages, while using Python and NumPy for higher-level logic. This feature provides the flexibility to build fast and efficient numerical programs.
7. Multidimensional Data Manipulation

.Purpose: NumPy’s array operations are extended to multiple dimensions, allowing for manipulation of data in higher-dimensional spaces (e.g., 3D, 4D arrays).

.Advantage: This is crucial for scientific computing tasks that involve simulations, image processing, or any data analysis involving multiple dimensions.
8. Support for Random Number Generation

.Purpose: NumPy comes with a submodule (numpy.random) that supports generating random numbers from various distributions.

.Advantage: This is essential for statistical simulations, machine learning, and Monte Carlo methods, where random sampling is required.
9. Data Masking and Missing Data Handling

.Purpose: NumPy supports masked arrays, which allow for ignoring certain elements in an array when performing computations.

.Advantage: This feature is useful when handling datasets with missing or invalid data, allowing analysts to apply mathematical operations only to valid data.
10. Cross-platform Compatibility

.Purpose: NumPy is designed to work efficiently on a variety of platforms (Windows, macOS, Linux).

.Advantage: This makes it accessible for a wide range of users and applications, from scientific research on high-performance clusters to personal projects on personal computers.

Summary of Benefits:

.Speed: NumPy is faster than Python's native list-based operations.

.Memory Efficiency: Efficient memory usage due to contiguous data storage.

.Convenience: Easy handling of mathematical, statistical, and linear algebraic operations.

.Integration: Seamless with other scientific and data analysis libraries.

.Flexibility: Powerful broadcasting and vectorized operations.

Overall, NumPy is a foundational tool that makes Python highly suitable for numerical analysis and scientific computing, offering both performance and simplicity.













**Q2.Compare and contrast np.mean() and np.average() functionsin NumPy. When would you use one over the other?**

Ans. In NumPy, both np.mean() and np.average() are used to compute the average of an array, but they differ in their behavior and specific use cases. Let’s compare and contrast them and see when each should be used.

1. Basic Functionality

.np.mean():

.Definition: Computes the arithmetic mean (average) of the elements in an array.

.Usage: np.mean(arr) simply sums all the elements in the array arr and divides by the number of elements.

.Example:


In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4])
mean_value = np.mean(arr)  # Output: 2.5


.np.average():

.Definition: Computes a weighted average of the elements in an array. If no weights are provided, it behaves the same as np.mean().

.Usage: np.average(arr, weights=w) allows you to compute a weighted average by giving each element of the array a weight, affecting its contribution to the final average.

.Example (With weights):

In [2]:
arr = np.array([1, 2, 3, 4])
weights = np.array([0.1, 0.2, 0.3, 0.4])
weighted_avg = np.average(arr, weights=weights)  # Output: 3.0


2. Weighted Average in np.average()

The key distinction is that np.average() supports a weights parameter, which allows for calculating a weighted mean. In a weighted mean, each element of the array contributes differently to the result based on its associated weight.

3.  When to Use np.mean()

Use np.mean() when you want a simple, unweighted average. This is appropriate for most cases where all elements contribute equally to the result.

Example: If you want the average temperature for a given day based on hourly measurements, where each measurement is equally important.

In [3]:
temperatures = np.array([70, 72, 68, 65])
avg_temperature = np.mean(temperatures)  # Output: 68.75


4. When to Use np.average()

Use np.average() when you need to compute a weighted average, where certain elements should contribute more heavily to the final result based on their importance or relevance.

Example: If you want the average grade for a student, but different assignments have different weights (e.g., final exam has more weight than a quiz).

In [4]:
grades = np.array([85, 90, 78])
weights = np.array([0.2, 0.5, 0.3])  # Final exam has more weight
weighted_average = np.average(grades, weights=weights)  # Output: 86.1


5.  Performance

Both np.mean() and np.average() are efficient, but if you're simply calculating the arithmetic mean without weights, np.mean() is slightly faster since it has fewer operations to perform.

Summary of When to Use:

.Use np.mean() when you need a simple, unweighted arithmetic average.

.Use np.average() when you need a weighted average or when different elements should contribute to the result differently based on a weight system.

In cases where no weights are needed, both functions will give the same result.



**Q3. Describe the methodes or reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.**

Ans. Reversing a NumPy array along different axes can be done using a variety of methods, depending on the dimensionality of the array and the axis along which you want to reverse the elements. Below, I will explain the methods for reversing arrays along different axes, and provide examples for both 1D and 2D arrays.

Methods for Reversing a NumPy Array

1. Using slicing ([::-1]): This is the most common and Pythonic way to reverse a NumPy array. You can use slicing to reverse the array along a specific axis.

2. Using np.flip(): NumPy provides a built-in function np.flip(), which allows you to reverse an array along any specified axis.

3. Using np.flipud() and np.fliplr(): These functions are specific to 2D arrays. np.flipud() reverses the array along the vertical axis (up-down), while np.fliplr() reverses it along the horizontal axis (left-right).

Reversing a 1D Array

Method 1: Using slicing ([::-1])

In [5]:
import numpy as np

arr_1d = np.array([1, 2, 3, 4, 5])
reversed_arr = arr_1d[::-1]
print(reversed_arr)


[5 4 3 2 1]


Method 2: Using np.flip()

In [6]:
reversed_arr = np.flip(arr_1d)
print(reversed_arr)


[5 4 3 2 1]


Reversing a 2D

Let's take a 2D array and explore how to reverse it along different axes.

In [7]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])


Method 1: Reverse along the vertical axis (rows) using slicing

In [8]:
reversed_arr_rows = arr_2d[::-1, :]
print(reversed_arr_rows)


[[7 8 9]
 [4 5 6]
 [1 2 3]]


Method 2: Reverse along the vertical axis using np.flipud()

In [9]:
reversed_arr_rows = np.flipud(arr_2d)
print(reversed_arr_rows)


[[7 8 9]
 [4 5 6]
 [1 2 3]]


Method 3: Reverse along the horizontal axis (columns) using slicing

In [10]:
reversed_arr_columns = arr_2d[:, ::-1]
print(reversed_arr_columns)


[[3 2 1]
 [6 5 4]
 [9 8 7]]


Method 4: Reverse along the horizontal axis using np.fliplr()

In [11]:
reversed_arr_columns = np.fliplr(arr_2d)
print(reversed_arr_columns)


[[3 2 1]
 [6 5 4]
 [9 8 7]]


Method 5: Reverse along both axes using slicing

In [12]:
reversed_arr_both_axes = arr_2d[::-1, ::-1]
print(reversed_arr_both_axes)


[[9 8 7]
 [6 5 4]
 [3 2 1]]


Method 6: Reverse along both axes using np.flip() with axis

In [13]:
reversed_arr_both_axes = np.flip(arr_2d, axis=(0, 1))
print(reversed_arr_both_axes)


[[9 8 7]
 [6 5 4]
 [3 2 1]]


Summary of Methods:

.1D Array:

.Use arr[::-1] or np.flip(arr) to reverse the elements.

.2D Array:

.Reverse rows (vertical axis) using arr[::-1, :] or np.flipud(arr).
.Reverse columns (horizontal axis) using arr[:, ::-1] or np.fliplr(arr).
.Reverse both axes using arr[::-1, ::-1] or np.flip(arr, axis=(0, 1)).

**Q4. How can you determine the data types of elements in a NumPy array? Dicuss the importance o data types in memory management and performance.**

Ans. In NumPy, you can determine the data type (or dtype) of the elements in an array using the .dtype attribute. Here's an example:

In [14]:
import numpy as np

# Create a NumPy array
arr = np.array([1, 2, 3])

# Determine the data type
print(arr.dtype)


int64


Importance of Data Types in Memory Management and Performance:

1. Memory Management:

.Data types in NumPy determine how much memory is allocated for each element. For example, an int32 array uses 4 bytes per element, while an int64 array uses 8 bytes. Choosing the appropriate data type based on the range of values helps optimize memory usage.

.For large datasets, using unnecessarily large data types leads to excessive memory consumption, which can slow down computations and lead to memory overflow issues.

 2. Performance:

.NumPy is designed for fast numerical computations, and the speed of operations is directly tied to the data types used. Operations on smaller data types (e.g., int32 or float32) are generally faster than those on larger ones (e.g., int64 or float64) because smaller types fit better in CPU caches, leading to quicker access times.

.Certain vectorized operations or linear algebra routines in NumPy can take advantage of the specific size and structure of data types, leading to better CPU/GPU utilization.

**Q5. Define ndarrays in NumPy and explain their key features. How do they differ from standard python lists?**

Ans. In NumPy, ndarray (short for N-dimensional array) is the fundamental data structure used for numerical computations. It represents a grid of values, all of the same type, indexed by a tuple of non-negative integers. These arrays can be multi-dimensional, from 1D (vectors) to nD (matrices, tensors, etc.).

Key Features of ndarray:

1. Homogeneous Data Type:

All elements of an ndarray must be of the same data type (dtype). This contrasts with Python lists, which can hold mixed types. Having a homogeneous data type allows for efficient memory management and faster computation.

2. Fixed Size:

Once an ndarray is created, its size is fixed. You cannot dynamically add or remove elements as you can with Python lists. This fixed-size nature leads to optimized memory usage.

3. N-Dimensional:

NumPy arrays can be multi-dimensional. While a Python list can have nested lists to represent higher dimensions, NumPy's ndarray provides a more compact and efficient way to handle multi-dimensional data. For example, a 2D array can represent matrices, and 3D or higher arrays can represent tensors.

4. Vectorized Operations:

ndarray supports element-wise operations without the need for explicit loops, enabling fast and efficient computation (called vectorization). For example:
python

In [15]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2  # Element-wise addition


5. Efficient Memory Layout:

ndarray objects store data in contiguous blocks of memory, ensuring that operations on large arrays are performed efficiently. In contrast, Python lists are arrays of pointers to objects, which is less memory-efficient.

6. Broadcasting:

NumPy arrays support broadcasting, a feature that allows arrays of different shapes to be combined in arithmetic operations. For example, you can add a scalar to an array or add two arrays of different shapes under certain conditions.

7. Built-in Mathematical Functions:

NumPy provides a rich set of mathematical operations and functions that are optimized for performance when working with ndarray objects, such as linear algebra operations, statistical functions, and random number generation.

8. Slicing and Indexing:

Like Python lists, ndarray supports slicing, but it is much more powerful. You can slice along multiple dimensions and access subarrays directly, making it easier to manipulate data.

In [16]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr[0, 1])  # Access element at first row, second column
print(arr[:, 1])  # Access entire second column


2
[2 5]


In summary, NumPy’s ndarray is optimized for numerical computation and large-scale data handling, whereas Python lists offer more flexibility but come at a cost in terms of memory efficiency and performance.


**Q6. Analyze the performance  benefites of NumPy arrays over Python lists for large-scale numerical operations .**

Ans. NumPy arrays (ndarray) provide significant performance benefits over Python lists, especially for large-scale numerical operations. These benefits stem from memory efficiency, faster computation due to vectorization, and integration with low-level libraries. Below is a detailed analysis of the performance advantages:

1. Memory Efficiency

Fixed and Contiguous Memory Allocation:

.NumPy arrays store elements in contiguous blocks of memory, which reduces overhead and allows the system to access elements faster. In contrast, Python lists store references to objects, which means each element is a pointer to a separate memory location, leading to more memory overhead.

.In large datasets, the memory savings from NumPy’s compact storage becomes substantial, allowing more data to fit into memory and reducing the likelihood of needing to swap data in and out of memory (paging), which can slow down computation.

Examples:

In [17]:
import numpy as np
import sys

# Large list and array with 1 million elements
python_list = list(range(1000000))
numpy_array = np.array(range(1000000))

print(sys.getsizeof(python_list))  # Memory used by Python list
print(numpy_array.nbytes)          # Memory used by NumPy array


8000056
8000000


2. Vectorized Operations

Eliminating Loops:

.One of the most important performance benefits of NumPy is vectorization, which allows operations to be performed element-wise on arrays without needing explicit loops. Python loops are slow because of the overhead of interpreting each loop step. NumPy eliminates this by executing operations in compiled C
code underneath, bypassing Python’s interpreter.

.This results in O(n) operations being done in bulk, which drastically improves performance for large-scale computations.

Example:

In [18]:
import numpy as np

# Using NumPy for vectorized operations
arr = np.array([1, 2, 3, 4, 5])
result = arr * 2  # Vectorized operation, each element is multiplied by 2


3. Optimized Low-Level Computations

.NumPy operations are implemented in low-level C and Fortran, which are much faster than the Python interpreter. This allows it to leverage highly optimized libraries like BLAS (Basic Linear Algebra Subprograms) and LAPACK (Linear Algebra Package) for matrix operations, making NumPy very efficient for tasks such as linear algebra, Fourier transforms, and random number generation.

.These optimizations make NumPy arrays faster for large numerical operations, particularly when dealing with multidimensional arrays or matrix computations.

4. Efficient Broadcasting Mechanism

.NumPy's broadcasting mechanism allows arrays of different shapes to be operated on without creating unnecessary copies or using inefficient loops. Broadcasting automatically expands the smaller array to match the size of the larger one, performing element-wise operations efficiently.

.In contrast, Python lists require explicit looping, which is much slower for large datasets.

Example of broadcasting:

In [19]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4])
result = arr1 + arr2  # Broadcasts scalar 4 to all elements of arr1


5. Pre-compiled Functions and Mathematical Libraries

.NumPy comes with a large set of pre-compiled mathematical functions (e.g., trigonometric, statistical, linear algebra) that operate directly on arrays. These functions are optimized for performance and avoid the overhead of function calls within Python loops.

For example, computing the mean of a large dataset using NumPy’s np.mean() is significantly faster than using Python's built-in functions.

Example:

In [20]:
import numpy as np
import time

arr = np.random.rand(10000000)

start_time = time.time()
np.mean(arr)  # Pre-compiled and optimized function
print("NumPy mean took:", time.time() - start_time)

# Python equivalent would be slower
start_time = time.time()
sum(arr) / len(arr)  # Python loop-based mean calculation
print("Python list mean took:", time.time() - start_time)


NumPy mean took: 0.0076138973236083984
Python list mean took: 1.0102553367614746


6. Support for Multidimensional Arrays

.While Python lists can represent multi-dimensional arrays using nested lists, this is inefficient for large datasets. NumPy arrays handle multidimensional data natively, offering better performance when working with tensors or matrices.

.Operations such as slicing, indexing, and matrix manipulations are far more efficient in NumPy due to its optimized handling of higher-dimensional data.
7. In-place Operations

.NumPy allows in-place operations, which can save both time and memory. By modifying the original array instead of creating new copies, NumPy avoids unnecessary data duplication.
.Python lists, on the other hand, often require the creation of new lists for modifications, especially when performing operations element-wise.
8. Parallelization

.Some NumPy operations are implicitly parallelized across multiple CPU cores, which significantly speeds up large-scale computations. Python's native list operations don’t have this advantage and often rely on single-threaded execution.
9. Avoiding Python Overheads

.Python lists incur various types of overheads, such as reference counting and dynamic type checks, every time an element is accessed. In contrast, NumPy arrays store elements in fixed-size, typed blocks of memory, which avoids these overheads and results in faster access and manipulation.

Performance Comparison Example:

In [22]:
import numpy as np
import time

# Large data size
size = 10000000

# NumPy array
arr = np.arange(size)
start = time.time()
arr = arr * 2  # Vectorized operation
print("NumPy array took:", time.time() - start)

# Python list
lst = list(range(size))
start = time.time()
lst = [x * 2 for x in lst]  # Loop-based operation
print("Python list took:", time.time() - start)


NumPy array took: 0.03197193145751953
Python list took: 1.4516642093658447


In this case, the NumPy array will perform significantly faster than the Python list, especially as the data size increases.


Conclusion:

NumPy arrays offer better memory efficiency, faster execution due to vectorization, and optimized low-level operations, making them far more suitable for large-scale numerical operations than Python lists. These features are crucial for scientific computing, machine learning, and data analysis tasks, where performance matters greatly when dealing with large datasets.



**Q7. Compare vstack() ans hstack() function in NumPy. Provide examples demonstrating their usage and output.**

Ans. In NumPy, vstack() and hstack() are used to stack arrays along different axes. They are useful for combining arrays either vertically (row-wise) or horizontally (column-wise). Let's break down how they work:

1. vstack() Function (Vertical Stack)

.Purpose: Stacks arrays vertically (i.e., row-wise). It combines arrays along the vertical (first) axis.

.Shape Requirement: Arrays to be stacked must have the same number of columns (second dimension).

Example of vstack():

In [23]:
import numpy as np

# Two 1D arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Using vstack to stack vertically
result = np.vstack((arr1, arr2))
print(result)


[[1 2 3]
 [4 5 6]]


Example with 2D arrays:

In [24]:
# Two 2D arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])

# Stack vertically
result = np.vstack((arr1, arr2))
print(result)


[[1 2]
 [3 4]
 [5 6]]


2. hstack() Function (Horizontal Stack)

.Purpose: Stacks arrays horizontally (i.e., column-wise). It combines arrays along the horizontal (second) axis.

.Shape Requirement: Arrays to be stacked must have the same number of rows (first dimension).

Example of hstack():

In [25]:
# Two 1D arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Using hstack to stack horizontally
result = np.hstack((arr1, arr2))
print(result)


[1 2 3 4 5 6]


Example with 2D arrays:

In [26]:
# Two 2D arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Stack horizontally
result = np.hstack((arr1, arr2))
print(result)


[[1 2 5 6]
 [3 4 7 8]]


Additional Notes:

.Dimension Transformation: When stacking 1D arrays using vstack(), the output will be 2D (each array becomes a row). When stacking 1D arrays with hstack(), the result remains 1D.

Both functions are very useful in merging datasets, particularly when working with tabular or matrix-like data.








**Q8. Explain the difference between fliplr() and flipud() methods in Numpy, including their effects on various array dimensions.**

Ans. In NumPy, the fliplr() and flipud() functions are used to reverse the order of elements along specific axes of a 2D array. They both flip the array, but they work on different dimensions:

1. np.fliplr() (Flip Left to Right):

.It flips the array horizontally, meaning it reverses the order of elements
along the columns (axis 1).

.This is equivalent to mirroring the array along the vertical axis.

.It requires at least a 2D array, and if applied to a higher-dimensional array, it affects only the last two dimensions.

Example:

In [1]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.fliplr(arr))


[[3 2 1]
 [6 5 4]]


2. np.flipud() (Flip Up to Down):

.It flips the array vertically, meaning it reverses the order of elements along the rows (axis 0).

.This is equivalent to mirroring the array along the horizontal axis.

.It can be applied to any array with 2 or more dimensions, and it only affects the rows.

Example:

In [2]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.flipud(arr))


[[4 5 6]
 [1 2 3]]


Summary of Differences:

.np.fliplr() flips the array horizontally, reversing the order of columns.

.np.flipud() flips the array vertically, reversing the order of rows.

Behavior with 3D Arrays:

.Both fliplr() and flipud() only affect the last two dimensions in a 3D array.

Example (for fliplr()):

In [3]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(np.fliplr(arr))


[[[3 4]
  [1 2]]

 [[7 8]
  [5 6]]]


Example (for flipud()):

In [4]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(np.flipud(arr))


[[[5 6]
  [7 8]]

 [[1 2]
  [3 4]]]


Each function serves a specific need for flipping elements across different axes, depending on whether you want to reverse rows or columns in an array.



**Q9. Discuss the functionalty of the array-split() method in NumPy. How does it handle uneven splits?**

Ans. The np.array_split() method in NumPy is used to divide an array into sub-arrays along a specified axis. Unlike np.split(), which requires the array to be split into equal-sized chunks, np.array_split() can handle uneven splits, making it more flexible when dealing with arrays that cannot be evenly divided.

Syntax:

In [ ]:
numpy.array_split(array, indices_or_sections, axis=0)


. array: The array to be split.

. indices_or_sections: This can be either:

. An integer specifying the number of sub-arrays to split the array into.

   .A list or array of indices specifying where the splits should occur.

.axis: The axis along which to split the array (default is axis 0).

.Key Differences from np.split():

.np.split() throws an error if the array cannot be evenly split.

.np.array_split() allows uneven splits and distributes the remaining elements among the sub-arrays.

Handling Uneven Splits:

When the array cannot be split evenly, the array_split() method will divide it into sub-arrays as evenly as possible, placing the excess elements in the earlier sub-arrays.

Example 1: Splitting an array evenly

In [7]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
result = np.array_split(arr, 3)
print(result)


[array([1, 2]), array([3, 4]), array([5, 6])]


Example 2: Uneven split

If the array length cannot be evenly divided by the number of splits, array_split() distributes the extra elements to the first few sub-arrays.

In [8]:
arr = np.array([1, 2, 3, 4, 5])
result = np.array_split(arr, 3)
print(result)


[array([1, 2]), array([3, 4]), array([5])]


Example 3: Specifying exact split points using indices

You can also pass a list of indices to array_split() to specify the split points manually.

In [9]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
result = np.array_split(arr, [3, 5])
print(result)


[array([1, 2, 3]), array([4, 5]), array([6, 7])]


Summary:

.np.array_split() is flexible for dividing arrays, especially when the division cannot be done evenly.

.When the split is uneven, it allocates the excess elements to the earlier sub-arrays.

.It works along a specified axis and can handle both integer-based splits and index-based splits.

This method is useful when the size of the input array may not match the desired number of sub-arrays exactly.


**Q10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?**

Ans. Vectorization and broadcasting are two fundamental concepts in NumPy that allow for efficient array operations by minimizing explicit loops and taking advantage of optimized low-level implementations. Both contribute to speeding up array computations, especially when dealing with large datasets.

1. Vectorization in NumPy

Vectorization refers to the process of applying operations over entire arrays (vectors, matrices) element-wise, without the need for explicit Python loops. Instead of iterating over elements manually, vectorized operations enable NumPy to use optimized, low-level C and Fortran code for these operations, resulting in significant performance improvements

Key Features of Vectorization:

.Element-wise operations: Vectorized functions operate element-wise on arrays. For instance, arithmetic operations like addition, subtraction, multiplication, etc., can be applied to arrays directly, and NumPy will execute them on all elements simultaneously.

.Performance: Since NumPy operations are implemented in C and run at compiled speeds, they are much faster than equivalent Python loops.

.Code simplicity: Vectorized code is usually more concise and readable, as operations are expressed directly on arrays.

Example of Vectorization:


In [1]:
import numpy as np

# Without vectorization (using Python loops)
arr = np.array([1, 2, 3, 4])
result = []
for x in arr:
    result.append(x * 2)
print(result)  # Output: [2, 4, 6, 8]

# With vectorization (NumPy)
result = arr * 2
print(result)  # Output: [2 4 6 8]


[2, 4, 6, 8]
[2 4 6 8]


2. Broadcasting in NumPy

Broadcasting is a mechanism that allows NumPy to perform element-wise operations on arrays of different shapes, by automatically expanding (or "broadcasting") smaller arrays to match the shape of larger arrays. This enables operations like addition, subtraction, multiplication, etc., to be performed on arrays of different dimensions without needing explicit reshaping or replication.

Key Features of Broadcasting:

.Automatic shape alignment: Broadcasting makes it possible to apply operations between arrays of different shapes by expanding the smaller array along dimensions where necessary.

.Memory efficiency: Instead of creating full-size copies of the smaller array, broadcasting allows NumPy to work as if the smaller array has been expanded without actually replicating data, saving both time and memory.

.Flexible operations: Broadcasting allows operations to be applied to arrays that are not of the same shape, as long as the shapes are compatible according to specific rules.

Rules of Broadcasting:

1. If the two arrays differ in the number of dimensions, the one with fewer dimensions is padded with ones on its left (for example, a 1D array will be treated as 2D by adding a leading axis).
2. Arrays are compatible for broadcasting if, for every dimension, they are either equal, or one of them is 1.
3. The arrays will be broadcasted to a common shape, and element-wise operations will be performed.

Example of Broadcasting:


In [1]:
import numpy as np

# 1D array (shape: (3,))
arr1 = np.array([1, 2, 3])

# 2D array (shape: (3, 3))
arr2 = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90]])

# Broadcasting the 1D array to the shape of the 2D array
result = arr1 + arr2
print(result)


[[11 22 33]
 [41 52 63]
 [71 82 93]]


In this case, arr1 (shape (3,)) is broadcasted to match the shape of arr2 (shape (3, 3)). Broadcasting expands arr1 along the rows so that it can be added to arr2 element-wise.


Broadcasting Example with Different Shapes:

In [2]:
# Scalar broadcasting
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
result = arr3 + 10  # Broadcasting scalar value
print(result)


[[11 12 13]
 [14 15 16]]


Contributions to Efficient Array Operations:
1. Performance Optimization:

.Vectorization enables computations to be performed at C-level speed, bypassing the slow Python interpreter and avoiding explicit loops.

.Broadcasting reduces the need for memory-expensive operations like replicating arrays. It allows smaller arrays to participate in operations with larger arrays efficiently.
2. Code Simplification:

.Both vectorization and broadcasting allow you to express operations in a concise, readable form, improving the clarity of code.
3. Memory Efficiency:

.Broadcasting saves memory by avoiding the need to explicitly expand arrays. This is crucial when dealing with large datasets.

Summary:
Vectorization refers to performing operations on arrays without explicit loops, enhancing performance and simplifying code.
Broadcasting allows operations on arrays of different shapes by expanding the smaller array to match the dimensions of the larger one, making computations both efficient and memory-saving.

Summary:

.Vectorization refers to performing operations on arrays without explicit loops, enhancing performance and simplifying code.

.Broadcasting allows operations on arrays of different shapes by expanding the smaller array to match the dimensions of the larger one, making computations both efficient and memory-saving.






# ***Practical Questions***

---



---

Q1.Create a 3*3 NumPy array with randam integers between 1 and 100. Then, interchange its rows and columns.

In [2]:
import numpy as np

# Creating a 3x3 array with random integers between 1 and 100
array = np.random.randint(1, 101, size=(3, 3))

# Interchanging rows and columns (transpose)
transposed_array = array.T

array, transposed_array


(array([[24, 72,  6],
        [54, 74,  9],
        [ 1, 37, 73]]),
 array([[24, 54,  1],
        [72, 74, 37],
        [ 6,  9, 73]]))

Q2. Generate a 1D NumPy array with 10 elements.Reshape it into a 2 * 5 array , then into a 5 * 2 array.

In [3]:
# Creating a 1D array with 10 elements
array_1d = np.arange(10)

# Reshaping into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)

# Reshaping the 2x5 array into a 5x2 array
array_5x2 = array_2x5.reshape(5, 2)

array_1d, array_2x5, array_5x2


(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]))

Q3. Create a 4 * 4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6 * 6 array.

In [4]:
# Creating a 4x4 array with random float values
array_4x4 = np.random.rand(4, 4)

# Adding a border of zeros to make it a 6x6 array
array_with_border = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

array_4x4, array_with_border


(array([[0.67574862, 0.92768579, 0.91058365, 0.86683458],
        [0.94782842, 0.05668473, 0.78811409, 0.07500865],
        [0.895186  , 0.23459531, 0.3036728 , 0.54388645],
        [0.40826038, 0.35575884, 0.12900875, 0.86735897]]),
 array([[0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ],
        [0.        , 0.67574862, 0.92768579, 0.91058365, 0.86683458,
         0.        ],
        [0.        , 0.94782842, 0.05668473, 0.78811409, 0.07500865,
         0.        ],
        [0.        , 0.895186  , 0.23459531, 0.3036728 , 0.54388645,
         0.        ],
        [0.        , 0.40826038, 0.35575884, 0.12900875, 0.86735897,
         0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ]]))

Q4. Using NumPy, create an array of integers from 10 to 60 with a step of 5

In [5]:
# Creating an array of integers from 10 to 60 with a step of 5
array_step = np.arange(10, 61, 5)

array_step


array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

Q5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case trensformations (uppercase, lowercase, title case, etc.) to each element.

In [6]:
import numpy as np

# Create the NumPy array of strings
array = np.array(['python', 'numpy', 'pandas'])

# Apply uppercase transformation
upper_case = np.char.upper(array)

# Apply lowercase transformation
lower_case = np.char.lower(array)

# Apply title case transformation
title_case = np.char.title(array)

print("Original array:", array)
print("Uppercase:", upper_case)
print("Lowercase:", lower_case)
print("Title case:", title_case)


Original array: ['python' 'numpy' 'pandas']
Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Title case: ['Python' 'Numpy' 'Pandas']


Q6. Generate a Numpy array of words, insert a space between each character of every word in the array.

In [7]:
import numpy as np

# Create the NumPy array of words
array = np.array(['python', 'numpy', 'pandas'])

# Insert a space between each character of every word
spaced_array = np.char.join(' ', array)

print("Original array:", array)
print("Spaced array:", spaced_array)


Original array: ['python' 'numpy' 'pandas']
Spaced array: ['p y t h o n' 'n u m p y' 'p a n d a s']


Q7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [8]:
import numpy as np

# Creating two 2D NumPy arrays
array1 = np.array([[10, 20, 30], [40, 50, 60]])
array2 = np.array([[1, 2, 3], [4, 5, 6]])

# Element-wise addition
addition = np.add(array1, array2)

# Element-wise subtraction
subtraction = np.subtract(array1, array2)

# Element-wise multiplication
multiplication = np.multiply(array1, array2)

# Element-wise division
division = np.divide(array1, array2)

print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("Addition:\n", addition)
print("Subtraction:\n", subtraction)
print("Multiplication:\n", multiplication)
print("Division:\n", division)


Array 1:
 [[10 20 30]
 [40 50 60]]
Array 2:
 [[1 2 3]
 [4 5 6]]
Addition:
 [[11 22 33]
 [44 55 66]]
Subtraction:
 [[ 9 18 27]
 [36 45 54]]
Multiplication:
 [[ 10  40  90]
 [160 250 360]]
Division:
 [[10. 10. 10.]
 [10. 10. 10.]]


Q8. Use NumPy to create  5*5 identity matrix, then extract its diagonal elements.

In [9]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)

print("Identity Matrix:\n", identity_matrix)
print("Diagonal Elements:", diagonal_elements)


Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements: [1. 1. 1. 1. 1.]


Q9. Generate a NumPy array of 100 random intrgers between 0 qand 1000. find and display all prime numbers in this array.

In [10]:
import numpy as np

# Step 1: Generate a NumPy array of 100 random integers between 0 and 1000
random_array = np.random.randint(0, 1001, size=100)

# Step 2: Define a function to check if a number is prime
def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(np.sqrt(num)) + 1):
        if num % i == 0:
            return False
    return True

# Step 3: Apply the prime checking function to the array and extract primes
prime_numbers = np.array([num for num in random_array if is_prime(num)])

# Display the results
print("Random Array:\n", random_array)
print("Prime Numbers in the Array:\n", prime_numbers)


Random Array:
 [846 765 478 739 463 937 292 274  45  26 953 675 539  24 844 522 787 991
 889 159 635 977 187 893 714 443 847 329 629 117 784 225 782 411 234 226
 891 211 634 745 417 617 518 617 162 795 996 715 354 319 392 183 102 596
 801  33 429 303 396 822 672 910 447 610 195 142 449 839 565 811 694  23
 696 732 738 484 615 555 412 443  46 343 194 946 724  55 355 379 767 729
   2 513 812 981 386  31 555 445 694 685]
Prime Numbers in the Array:
 [739 463 937 953 787 991 977 443 211 617 617 449 839 811  23 443 379   2
  31]


Q10. Create a NumPy array representing daily temperatures for a month. calculate and dsiplay the weekly.

In [ ]:
import numpy as np

# Step 1: Generate a NumPy array representing daily temperatures for 30 days
daily_temperatures = np.random.uniform(low=15, high=35, size=30)  # Assuming temperatures between 15°C and 35°C

# Step 2: Reshape the array into 4 weeks (7 days each)
weekly_temperatures = daily_temperatures.reshape(4, 7)

# Step 3: Calculate the average temperature for each week
weekly_averages = np.mean(weekly_temperatures, axis=1)

# Display the results
print("Daily Temperatures (30 Days):\n", daily_temperatures)
print("\nWeekly Temperatures:\n", weekly_temperatures)
print("\nAverage Weekly Temperatures:\n", weekly_averages)
